# Generated by Django 3.2.6 on 2021-08-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textual', models.CharField(max_length=200)),
                ('image', models.FileField(null=True, upload_to='')),
                ('exception', models.TextField(null=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
