# Generated by Django 3.2.6 on 2021-08-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210817_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedfunction',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
